name: Release pipeline

on:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'main'

jobs:
  build-and-analyze:
    uses: ./.github/workflows/build-and-analyze.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-push:
    runs-on: ubuntu-latest
    needs: build-and-analyze
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/shipping-service:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/shipping-service:${{ github.sha }}
  
  deploy:
    needs: docker-push
    uses: ./.github/workflows/deploy.yaml
    with:
        ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'staging' && 'staging' || github.ref_name == 'develop' && 'dev' }}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    
    